package hooks

import (
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"strings"
	"sync"

	"github.com/connix-io/conclaude/internal/config"
	"github.com/connix-io/conclaude/internal/logger"
	"github.com/connix-io/conclaude/internal/hookdata"
	"github.com/connix-io/conclaude/internal/hookdata/payloads"
	"github.com/gobwas/glob"
)

var (
	cachedConfig *config.ConclaudeConfig
	configMutex  sync.RWMutex
)

// createSessionLoggerFromPayload creates a session logger from any payload that has SessionID.
func createSessionLoggerFromPayload(sessionID string) (*slog.Logger, error) {
	loggingConfig := hookdata.LoggingConfig{}
	if err := logger.CreateSessionLogger(sessionID, &loggingConfig); err != nil {
		return nil, fmt.Errorf("failed to create session logger: %w", err)
	}
	return logger.GetLogger(), nil
}

// getConfig loads configuration with caching to avoid repeated file system operations.
func getConfig() (*config.ConclaudeConfig, error) {
	configMutex.RLock()
	if cachedConfig != nil {
		defer configMutex.RUnlock()

		return cachedConfig, nil
	}
	configMutex.RUnlock()

	configMutex.Lock()
	defer configMutex.Unlock()

	// Double-check locking pattern
	if cachedConfig != nil {
		return cachedConfig, nil
	}

	cfg, err := config.LoadConfig()
	if err != nil {
		return nil, err
	}

	cachedConfig = cfg

	return cachedConfig, nil
}

// ReadPayloadFromStdin reads and validates hook payload from stdin.
func ReadPayloadFromStdin(payload any) error {
	data, err := io.ReadAll(os.Stdin)
	if err != nil {
		return fmt.Errorf("failed to read from stdin: %w", err)
	}

	if err := json.Unmarshal(data, payload); err != nil {
		return fmt.Errorf("failed to parse JSON payload from stdin: %w", err)
	}

	return nil
}

// HandleHookResult standardizes hook result processing and process exit codes.
func HandleHookResult(handler func() (hookdata.HookResult, error)) error {
	result, err := handler()
	if err != nil {
		fmt.Fprintf(os.Stderr, "❌ Hook failed: %v\n", err)
		os.Exit(1)
	}

	if result.Blocked != nil && *result.Blocked && result.Message != nil {
		fmt.Fprintf(os.Stderr, "❌ Hook blocked: %s\n", *result.Message)
		os.Exit(2)
	}

	os.Exit(0)

	return nil // Never reached
}

// SessionProvider is an interface for payloads that can provide a session ID.
type SessionProvider interface {
	GetSessionID() string
	Validate() error
}

// TypedHookHandler represents a typed hook handler function with dependencies.
type TypedHookHandler[T SessionProvider] func(*slog.Logger, *config.ConclaudeConfig, T) (hookdata.HookResult, error)

// WithLoggerAndPayload wraps a typed hook handler to work with HandleHookResult.
func WithLoggerAndPayload[T SessionProvider](handler TypedHookHandler[T]) func() (hookdata.HookResult, error) {
	return func() (hookdata.HookResult, error) {
		// Read and parse the full payload
		var payload T
		if err := ReadPayloadFromStdin(&payload); err != nil {
			return hookdata.HookResult{}, err
		}

		// Validate the payload
		if err := payload.Validate(); err != nil {
			return hookdata.HookResult{}, err
		}

		// Load configuration once
		cfg, err := getConfig()
		if err != nil {
			return hookdata.HookResult{}, fmt.Errorf("failed to load configuration: %w", err)
		}

		// Create session logger using the payload's session ID
		sessionLogger, err := createSessionLoggerFromPayload(payload.GetSessionID())
		if err != nil {
			return hookdata.HookResult{}, err
		}

		// Call the handler with logger, config, and typed payload
		return handler(sessionLogger, cfg, payload)
	}
}

// handlePreToolUseWithLogger handles PreToolUse hook events with dependency injection.
func handlePreToolUseWithLogger(logger *slog.Logger, cfg *config.ConclaudeConfig, payload payloads.PreToolUsePayload) (hookdata.HookResult, error) {
	if payload.ToolName == "" {
		return hookdata.HookResult{}, errors.New("missing required field: tool_name")
	}

	logger.Info("Processing PreToolUse hook",
		"session_id", payload.SessionID,
		"tool_name", payload.ToolName)

	// Check tool usage validation rules
	if result, err := checkToolUsageRules(cfg, &payload); err != nil {
		return hookdata.HookResult{}, err
	} else if result != nil {
		return *result, nil
	}

	fileModifyingTools := []string{"Write", "Edit", "MultiEdit", "NotebookEdit"}
	isFileModifying := slices.Contains(fileModifyingTools, payload.ToolName)

	if isFileModifying {
		if result, err := checkFileValidationRules(cfg, &payload); err != nil {
			return hookdata.HookResult{}, err
		} else if result != nil {
			return *result, nil
		}

		if result, err := checkAutoGeneratedFile(cfg, &payload); err != nil {
			return hookdata.HookResult{}, err
		} else if result != nil {
			return *result, nil
		}
	}

	return hookdata.NewSuccessResult(), nil
}

// HandlePreToolUse handles PreToolUse hook events fired before Claude executes any tool.
func HandlePreToolUse() (hookdata.HookResult, error) {
	return WithLoggerAndPayload(handlePreToolUseWithLogger)()
}

// checkToolUsageRules validates tool usage against configured rules.
func checkToolUsageRules(cfg *config.ConclaudeConfig, payload *payloads.PreToolUsePayload) (*hookdata.HookResult, error) {

	for _, rule := range cfg.Rules.ToolUsageValidation {
		if rule.Tool != payload.ToolName {
			continue
		}

		// Create regex pattern
		regex, err := regexp.Compile(rule.Pattern)
		if err != nil {
			slog.Warn("Invalid regex pattern in tool usage rule",
				"rule", rule.Tool,
				"pattern", rule.Pattern,
				"error", err)

			continue
		}

		// Check if pattern matches tool input
		inputJSON, _ := json.Marshal(payload.ToolInput)
		if regex.Match(inputJSON) {
			if rule.Action == "block" {
				message := "Tool usage blocked by rule: " + rule.Tool
				if rule.Message != nil {
					message = *rule.Message
				}
				result := hookdata.NewBlockedResult(message)

				return &result, nil
			}
		}
	}

	return nil, nil
}

// checkFileValidationRules validates file operations against configured rules.
func checkFileValidationRules(cfg *config.ConclaudeConfig, payload *payloads.PreToolUsePayload) (*hookdata.HookResult, error) {

	filePath := config.ExtractFilePath(payload.ToolInput)
	if filePath == nil {
		return nil, nil
	}

	cwd, err := os.Getwd()
	if err != nil {
		return nil, fmt.Errorf("failed to get current working directory: %w", err)
	}

	resolvedPath := filepath.Join(cwd, *filePath)
	relativePath, err := filepath.Rel(cwd, resolvedPath)
	if err != nil {
		relativePath = *filePath
	}

	// Check prevent root additions
	if cfg.Rules.PreventRootAdditions {
		if !strings.Contains(relativePath, string(filepath.Separator)) {
			// File is in root directory
			if _, err := os.Stat(resolvedPath); os.IsNotExist(err) {
				// File doesn't exist, so this would be a new addition
				message := fmt.Sprintf(
					"Blocked %s operation: preventRootAdditions rule prevents creating files at repository root. File: %s",
					payload.ToolName,
					resolvedPath,
				)
				result := hookdata.NewBlockedResult(message)

				return &result, nil
			}
		}
	}

	// Check uneditable files
	for _, pattern := range cfg.Rules.UneditableFiles {
		globPattern, err := glob.Compile(pattern)
		if err != nil {
			slog.Warn("Invalid glob pattern in uneditable files",
				"pattern", pattern,
				"error", err)

			continue
		}

		if globPattern.Match(relativePath) {
			message := fmt.Sprintf("File %s is marked as uneditable in configuration", relativePath)
			result := hookdata.NewBlockedResult(message)

			return &result, nil
		}
	}

	return nil, nil
}

// checkAutoGeneratedFile checks if file is auto-generated and should not be edited.
func checkAutoGeneratedFile(cfg *config.ConclaudeConfig, payload *payloads.PreToolUsePayload) (*hookdata.HookResult, error) {

	if !cfg.PreToolUse.PreventGeneratedFileEdits {
		return nil, nil
	}

	filePath := config.ExtractFilePath(payload.ToolInput)
	if filePath == nil {
		return nil, nil
	}

	if config.IsAutoGeneratedFile(*filePath) {
		message := "This file appears to be auto-generated and should not be edited manually"
		if cfg.PreToolUse.GeneratedFileMessage != nil {
			message = *cfg.PreToolUse.GeneratedFileMessage
		}
		result := hookdata.NewBlockedResult(message)

		return &result, nil
	}

	return nil, nil
}

// handlePostToolUseWithLogger handles PostToolUse hook events with dependency injection.
func handlePostToolUseWithLogger(logger *slog.Logger, cfg *config.ConclaudeConfig, payload payloads.PostToolUsePayload) (hookdata.HookResult, error) {
	logger.Info("Processing PostToolUse hook",
		"session_id", payload.SessionID,
		"tool_name", payload.ToolName)

	return hookdata.NewSuccessResult(), nil
}

// HandlePostToolUse handles PostToolUse hook events fired after Claude executes a tool.
func HandlePostToolUse() (hookdata.HookResult, error) {
	return WithLoggerAndPayload(handlePostToolUseWithLogger)()
}

// handleNotificationWithLogger handles Notification hook events with dependency injection.
func handleNotificationWithLogger(logger *slog.Logger, cfg *config.ConclaudeConfig, payload payloads.NotificationPayload) (hookdata.HookResult, error) {
	logger.Info("Processing Notification hook",
		"session_id", payload.SessionID,
		"message", payload.Message,
		"title", payload.Title)

	return hookdata.NewSuccessResult(), nil
}

// HandleNotification handles Notification hook events.
func HandleNotification() (hookdata.HookResult, error) {
	return WithLoggerAndPayload(handleNotificationWithLogger)()
}

// handleUserPromptSubmitWithLogger handles UserPromptSubmit hook events with dependency injection.
func handleUserPromptSubmitWithLogger(logger *slog.Logger, cfg *config.ConclaudeConfig, payload payloads.UserPromptSubmitPayload) (hookdata.HookResult, error) {
	logger.Info("Processing UserPromptSubmit hook",
		"session_id", payload.SessionID)

	return hookdata.NewSuccessResult(), nil
}

// HandleUserPromptSubmit handles UserPromptSubmit hook events.
func HandleUserPromptSubmit() (hookdata.HookResult, error) {
	return WithLoggerAndPayload(handleUserPromptSubmitWithLogger)()
}

// handleSessionStartWithLogger handles SessionStart hook events with dependency injection.
func handleSessionStartWithLogger(logger *slog.Logger, cfg *config.ConclaudeConfig, payload payloads.SessionStartPayload) (hookdata.HookResult, error) {
	logger.Info("Processing SessionStart hook",
		"session_id", payload.SessionID,
		"source", payload.Source)

	return hookdata.NewSuccessResult(), nil
}

// HandleSessionStart handles SessionStart hook events.
func HandleSessionStart() (hookdata.HookResult, error) {
	return WithLoggerAndPayload(handleSessionStartWithLogger)()
}

// handleStopWithLogger handles Stop hook events with dependency injection.
func handleStopWithLogger(logger *slog.Logger, cfg *config.ConclaudeConfig, payload payloads.StopPayload) (hookdata.HookResult, error) {
	logger.Info("Processing Stop hook",
		"session_id", payload.SessionID,
		"stop_hook_active", payload.StopHookActive)

	return hookdata.NewSuccessResult(), nil
}

// HandleStop handles Stop hook events.
func HandleStop() (hookdata.HookResult, error) {
	return WithLoggerAndPayload(handleStopWithLogger)()
}

// handleSubagentStopWithLogger handles SubagentStop hook events with dependency injection.
func handleSubagentStopWithLogger(logger *slog.Logger, cfg *config.ConclaudeConfig, payload payloads.SubagentStopPayload) (hookdata.HookResult, error) {
	logger.Info("Processing SubagentStop hook",
		"session_id", payload.SessionID,
		"stop_hook_active", payload.StopHookActive)

	return hookdata.NewSuccessResult(), nil
}

// HandleSubagentStop handles SubagentStop hook events.
func HandleSubagentStop() (hookdata.HookResult, error) {
	return WithLoggerAndPayload(handleSubagentStopWithLogger)()
}

// handlePreCompactWithLogger handles PreCompact hook events with dependency injection.
func handlePreCompactWithLogger(logger *slog.Logger, cfg *config.ConclaudeConfig, payload payloads.PreCompactPayload) (hookdata.HookResult, error) {
	logger.Info("Processing PreCompact hook",
		"session_id", payload.SessionID,
		"trigger", payload.Trigger)

	return hookdata.NewSuccessResult(), nil
}

// HandlePreCompact handles PreCompact hook events.
func HandlePreCompact() (hookdata.HookResult, error) {
	return WithLoggerAndPayload(handlePreCompactWithLogger)()
}
