package hooks

import (
	"encoding/json"
	"fmt"
	"io"
	"log/slog"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"sync"

	"github.com/connix-io/conclaude-go/internal/config"
	"github.com/connix-io/conclaude-go/internal/logger"
	"github.com/connix-io/conclaude-go/internal/types"
	"github.com/gobwas/glob"
)

var (
	cachedConfig *config.ConclaudeConfig
	configMutex  sync.RWMutex
)

// getConfig loads configuration with caching to avoid repeated file system operations
func getConfig() (*config.ConclaudeConfig, error) {
	configMutex.RLock()
	if cachedConfig != nil {
		defer configMutex.RUnlock()
		return cachedConfig, nil
	}
	configMutex.RUnlock()

	configMutex.Lock()
	defer configMutex.Unlock()
	
	// Double-check locking pattern
	if cachedConfig != nil {
		return cachedConfig, nil
	}

	cfg, err := config.LoadConfig()
	if err != nil {
		return nil, err
	}
	
	cachedConfig = cfg
	return cachedConfig, nil
}

// ReadPayloadFromStdin reads and validates hook payload from stdin
func ReadPayloadFromStdin(payload interface{}) error {
	data, err := io.ReadAll(os.Stdin)
	if err != nil {
		return fmt.Errorf("failed to read from stdin: %w", err)
	}

	if err := json.Unmarshal(data, payload); err != nil {
		return fmt.Errorf("failed to parse JSON payload from stdin: %w", err)
	}

	return nil
}

// HandleHookResult standardizes hook result processing and process exit codes
func HandleHookResult(handler func() (types.HookResult, error)) error {
	result, err := handler()
	if err != nil {
		fmt.Fprintf(os.Stderr, "❌ Hook failed: %v\n", err)
		os.Exit(1)
	}

	if result.Blocked != nil && *result.Blocked && result.Message != nil {
		fmt.Fprintf(os.Stderr, "❌ Hook blocked: %s\n", *result.Message)
		os.Exit(2)
	}

	os.Exit(0)
	return nil // Never reached
}

// HandlePreToolUse handles PreToolUse hook events fired before Claude executes any tool
func HandlePreToolUse() (types.HookResult, error) {
	var payload types.PreToolUsePayload
	if err := ReadPayloadFromStdin(&payload); err != nil {
		return types.HookResult{}, err
	}

	if err := payload.BasePayload.Validate(); err != nil {
		return types.HookResult{}, err
	}

	if payload.ToolName == "" {
		return types.HookResult{}, fmt.Errorf("missing required field: tool_name")
	}

	// Initialize logger
	loggingConfig := types.LoggingConfig{}
	if err := logger.CreateSessionLogger(payload.SessionID, &loggingConfig); err != nil {
		return types.HookResult{}, fmt.Errorf("failed to create session logger: %w", err)
	}

	slog.Info("Processing PreToolUse hook",
		"session_id", payload.SessionID,
		"tool_name", payload.ToolName)

	// Check tool usage validation rules
	if result, err := checkToolUsageRules(&payload); err != nil {
		return types.HookResult{}, err
	} else if result != nil {
		return *result, nil
	}

	fileModifyingTools := []string{"Write", "Edit", "MultiEdit", "NotebookEdit"}
	isFileModifying := false
	for _, tool := range fileModifyingTools {
		if payload.ToolName == tool {
			isFileModifying = true
			break
		}
	}

	if isFileModifying {
		if result, err := checkFileValidationRules(&payload); err != nil {
			return types.HookResult{}, err
		} else if result != nil {
			return *result, nil
		}

		if result, err := checkAutoGeneratedFile(&payload); err != nil {
			return types.HookResult{}, err
		} else if result != nil {
			return *result, nil
		}
	}

	return types.NewSuccessResult(), nil
}

// checkToolUsageRules validates tool usage against configured rules
func checkToolUsageRules(payload *types.PreToolUsePayload) (*types.HookResult, error) {
	cfg, err := getConfig()
	if err != nil {
		return nil, err
	}

	for _, rule := range cfg.Rules.ToolUsageValidation {
		if rule.Tool != payload.ToolName {
			continue
		}

		// Create regex pattern
		regex, err := regexp.Compile(rule.Pattern)
		if err != nil {
			slog.Warn("Invalid regex pattern in tool usage rule",
				"rule", rule.Tool,
				"pattern", rule.Pattern,
				"error", err)
			continue
		}

		// Check if pattern matches tool input
		inputJSON, _ := json.Marshal(payload.ToolInput)
		if regex.Match(inputJSON) {
			if rule.Action == "block" {
				message := fmt.Sprintf("Tool usage blocked by rule: %s", rule.Tool)
				if rule.Message != nil {
					message = *rule.Message
				}
				result := types.NewBlockedResult(message)
				return &result, nil
			}
		}
	}

	return nil, nil
}

// checkFileValidationRules validates file operations against configured rules
func checkFileValidationRules(payload *types.PreToolUsePayload) (*types.HookResult, error) {
	cfg, err := getConfig()
	if err != nil {
		return nil, err
	}

	filePath := config.ExtractFilePath(payload.ToolInput)
	if filePath == nil {
		return nil, nil
	}

	cwd, err := os.Getwd()
	if err != nil {
		return nil, fmt.Errorf("failed to get current working directory: %w", err)
	}

	resolvedPath := filepath.Join(cwd, *filePath)
	relativePath, err := filepath.Rel(cwd, resolvedPath)
	if err != nil {
		relativePath = *filePath
	}

	// Check prevent root additions
	if cfg.Rules.PreventRootAdditions {
		if !strings.Contains(relativePath, string(filepath.Separator)) {
			// File is in root directory
			if _, err := os.Stat(resolvedPath); os.IsNotExist(err) {
				// File doesn't exist, so this would be a new addition
				message := fmt.Sprintf("Blocked %s operation: preventRootAdditions rule prevents creating files at repository root. File: %s", 
					payload.ToolName, resolvedPath)
				result := types.NewBlockedResult(message)
				return &result, nil
			}
		}
	}

	// Check uneditable files
	for _, pattern := range cfg.Rules.UneditableFiles {
		globPattern, err := glob.Compile(pattern)
		if err != nil {
			slog.Warn("Invalid glob pattern in uneditable files",
				"pattern", pattern,
				"error", err)
			continue
		}

		if globPattern.Match(relativePath) {
			message := fmt.Sprintf("File %s is marked as uneditable in configuration", relativePath)
			result := types.NewBlockedResult(message)
			return &result, nil
		}
	}

	return nil, nil
}

// checkAutoGeneratedFile checks if file is auto-generated and should not be edited
func checkAutoGeneratedFile(payload *types.PreToolUsePayload) (*types.HookResult, error) {
	cfg, err := getConfig()
	if err != nil {
		return nil, err
	}

	if !cfg.PreToolUse.PreventGeneratedFileEdits {
		return nil, nil
	}

	filePath := config.ExtractFilePath(payload.ToolInput)
	if filePath == nil {
		return nil, nil
	}

	if config.IsAutoGeneratedFile(*filePath) {
		message := "This file appears to be auto-generated and should not be edited manually"
		if cfg.PreToolUse.GeneratedFileMessage != nil {
			message = *cfg.PreToolUse.GeneratedFileMessage
		}
		result := types.NewBlockedResult(message)
		return &result, nil
	}

	return nil, nil
}

// HandlePostToolUse handles PostToolUse hook events fired after Claude executes a tool
func HandlePostToolUse() (types.HookResult, error) {
	var payload types.PostToolUsePayload
	if err := ReadPayloadFromStdin(&payload); err != nil {
		return types.HookResult{}, err
	}

	if err := payload.BasePayload.Validate(); err != nil {
		return types.HookResult{}, err
	}

	// Initialize logger
	loggingConfig := types.LoggingConfig{}
	if err := logger.CreateSessionLogger(payload.SessionID, &loggingConfig); err != nil {
		return types.HookResult{}, fmt.Errorf("failed to create session logger: %w", err)
	}

	slog.Info("Processing PostToolUse hook",
		"session_id", payload.SessionID,
		"tool_name", payload.ToolName)

	return types.NewSuccessResult(), nil
}

// HandleNotification handles Notification hook events
func HandleNotification() (types.HookResult, error) {
	var payload types.NotificationPayload
	if err := ReadPayloadFromStdin(&payload); err != nil {
		return types.HookResult{}, err
	}

	if err := payload.BasePayload.Validate(); err != nil {
		return types.HookResult{}, err
	}

	// Initialize logger
	loggingConfig := types.LoggingConfig{}
	if err := logger.CreateSessionLogger(payload.SessionID, &loggingConfig); err != nil {
		return types.HookResult{}, fmt.Errorf("failed to create session logger: %w", err)
	}

	slog.Info("Processing Notification hook",
		"session_id", payload.SessionID,
		"message", payload.Message,
		"title", payload.Title)

	return types.NewSuccessResult(), nil
}

// HandleUserPromptSubmit handles UserPromptSubmit hook events
func HandleUserPromptSubmit() (types.HookResult, error) {
	var payload types.UserPromptSubmitPayload
	if err := ReadPayloadFromStdin(&payload); err != nil {
		return types.HookResult{}, err
	}

	if err := payload.BasePayload.Validate(); err != nil {
		return types.HookResult{}, err
	}

	// Initialize logger
	loggingConfig := types.LoggingConfig{}
	if err := logger.CreateSessionLogger(payload.SessionID, &loggingConfig); err != nil {
		return types.HookResult{}, fmt.Errorf("failed to create session logger: %w", err)
	}

	slog.Info("Processing UserPromptSubmit hook",
		"session_id", payload.SessionID)

	return types.NewSuccessResult(), nil
}

// HandleSessionStart handles SessionStart hook events
func HandleSessionStart() (types.HookResult, error) {
	var payload types.SessionStartPayload
	if err := ReadPayloadFromStdin(&payload); err != nil {
		return types.HookResult{}, err
	}

	if err := payload.BasePayload.Validate(); err != nil {
		return types.HookResult{}, err
	}

	// Initialize logger
	loggingConfig := types.LoggingConfig{}
	if err := logger.CreateSessionLogger(payload.SessionID, &loggingConfig); err != nil {
		return types.HookResult{}, fmt.Errorf("failed to create session logger: %w", err)
	}

	slog.Info("Processing SessionStart hook",
		"session_id", payload.SessionID,
		"source", payload.Source)

	return types.NewSuccessResult(), nil
}

// HandleStop handles Stop hook events
func HandleStop() (types.HookResult, error) {
	var payload types.StopPayload
	if err := ReadPayloadFromStdin(&payload); err != nil {
		return types.HookResult{}, err
	}

	if err := payload.BasePayload.Validate(); err != nil {
		return types.HookResult{}, err
	}

	// Initialize logger
	loggingConfig := types.LoggingConfig{}
	if err := logger.CreateSessionLogger(payload.SessionID, &loggingConfig); err != nil {
		return types.HookResult{}, fmt.Errorf("failed to create session logger: %w", err)
	}

	slog.Info("Processing Stop hook",
		"session_id", payload.SessionID,
		"stop_hook_active", payload.StopHookActive)

	return types.NewSuccessResult(), nil
}

// HandleSubagentStop handles SubagentStop hook events
func HandleSubagentStop() (types.HookResult, error) {
	var payload types.SubagentStopPayload
	if err := ReadPayloadFromStdin(&payload); err != nil {
		return types.HookResult{}, err
	}

	if err := payload.BasePayload.Validate(); err != nil {
		return types.HookResult{}, err
	}

	// Initialize logger
	loggingConfig := types.LoggingConfig{}
	if err := logger.CreateSessionLogger(payload.SessionID, &loggingConfig); err != nil {
		return types.HookResult{}, fmt.Errorf("failed to create session logger: %w", err)
	}

	slog.Info("Processing SubagentStop hook",
		"session_id", payload.SessionID,
		"stop_hook_active", payload.StopHookActive)

	return types.NewSuccessResult(), nil
}

// HandlePreCompact handles PreCompact hook events
func HandlePreCompact() (types.HookResult, error) {
	var payload types.PreCompactPayload
	if err := ReadPayloadFromStdin(&payload); err != nil {
		return types.HookResult{}, err
	}

	if err := payload.BasePayload.Validate(); err != nil {
		return types.HookResult{}, err
	}

	// Initialize logger
	loggingConfig := types.LoggingConfig{}
	if err := logger.CreateSessionLogger(payload.SessionID, &loggingConfig); err != nil {
		return types.HookResult{}, fmt.Errorf("failed to create session logger: %w", err)
	}

	slog.Info("Processing PreCompact hook",
		"session_id", payload.SessionID,
		"trigger", payload.Trigger)

	return types.NewSuccessResult(), nil
}