# yaml-language-server: $schema=https://github.com/connix-io/conclaude/releases/latest/download/conclaude-schema.json
# Conclaude YAML Configuration - Complete Default Configuration
# This configuration defines how conclaude handles Claude Code hook events
# All supported options are shown below with their default values

# Stop hook configuration - runs when Claude is about to stop
stop:
  # Commands to run during Stop hook
  # Each line is executed as a separate bash command
  # run: "echo 'Stop hook is not configured'"

  # Alternative structured command format with optional custom error messages
  # Each command can have its own error message, and control output display
  commands:
    - run: "spectr validate --all --strict"
      showStdout: true
      showStderr: true
      message: "OpenSpec validation failed - please fix errors before continuing"
      maxOutputLines: 100
    - run: "nix develop -c 'lint'"
      showStdout: true
      showStderr: true
      message: "Linter failed - please fix errors before continuing"
      maxOutputLines: 50
    - run: "nix develop -c 'tests'"
      showStdout: true
      showStderr: true
      message: "Tests failed - please fix errors before continuing"
      maxOutputLines: 200
    - run: "nix build ."
      showStdout: true
      showStderr: true
      message: "Build .#default failed - please fix errors before continuing"
      maxOutputLines: 100

  # Examples:
  # commands:
  #   - run: "echo 'Starting build...'"
  #     showStdout: true    # User/Claude sees: "Starting build..."
  #
  #   - run: "npm test"
  #     showStdout: true    # Show test results to user/Claude
  #     showStderr: true    # Show test errors to user/Claude
  #     message: "Tests failed - please fix failing tests before continuing"
  #
  #   - run: "npm run build"
  #     showStderr: true    # Only show build errors to user/Claude, hide stdout
  #     message: "Build failed - please fix compilation errors"

  # Infinite mode - allows Claude to continue automatically
  # When enabled, Claude receives the infiniteMessage to continue working
  # instead of ending the session after stop hook commands succeed
  infinite: false

  # Message to send when infinite mode is enabled
  infiniteMessage: "continue working on the task"

  # Alternative to infinite mode - run for a specific number of rounds
  # When set, Claude will continue for the specified number of rounds
  rounds: null
  # Example: rounds: 3

# Pre-tool-use hook configuration - runs before tools are executed
preToolUse:
  # Prevent Claude from creating or modifying files at the repository root
  # Helps maintain clean project structure
  preventRootAdditions: true

  # Files that Claude cannot edit, using glob patterns
  # Supports various glob patterns for flexible file protection
  uneditableFiles: []
  # Examples:
  # uneditableFiles:
  #   - "./package.json"      # specific file
  #   - "*.md"                # file extension
  #   - "src/**/*.ts"         # nested patterns
  #   - ".env*"               # environment files
  #   - "docs/**"             # entire directories
  #   - "{package,tsconfig}.json"  # multiple specific files

  # Tool usage validation rules - control which tools can be used on which files
  # Allows fine-grained control over tool usage based on file patterns
  toolUsageValidation: []
  # Examples:
  # toolUsageValidation:
  #   - tool: "Write"
  #     pattern: "**/*.js"
  #     action: "allow"
  #     message: "Writing to JavaScript files is allowed"
  #   - tool: "*"
  #     pattern: ".env*"
  #     action: "block"
  #     message: "Environment files cannot be modified"

  # Directories where file additions are prevented (in addition to root)
  # List of directory paths where new files cannot be created
  preventAdditions: []
  # Examples:
  # preventAdditions:
  #   - "dist"
  #   - "build"
  #   - "node_modules"

  # Prevent editing of auto-generated files (enabled by default)
  # Checks for common markers like "DO\ NOT\ EDIT", "Code\ generated\ by", etc.
  preventGeneratedFileEdits: false

  # Custom message when blocking auto-generated file edits
  # Available placeholders: {file_path}, {marker}
  generatedFileMessage: null
  # Example:
  # generatedFileMessage: "Cannot modify {file_path} - it contains '{marker}' indicating it's auto-generated"

# System notifications configuration
notifications:
  # Enable system notifications for hook execution
  enabled: true

  # List of hook names that should trigger notifications
  # Use ["*"] to receive notifications for all hooks
  # Common hook names: "Stop", "PreToolUse", "PostToolUse", "SessionStart", "UserPromptSubmit", "Notification", "SubagentStop", "PreCompact"
  hooks: ["*"]
  # Examples:
  # hooks: ["*"]                    # All hooks
  # hooks: ["Stop", "PreToolUse"]   # Only specific hooks
  # hooks: ["Stop"]                 # Only stop hook notifications

  # Show error notifications (hook failures, system errors)
  showErrors: false

  # Show success notifications (hook completion, successful operations)
  showSuccess: false

  # Show system event notifications (session start/end, configuration loaded)
  showSystemEvents: true
