stop:
  run: |
    nix build .
    nix develop -c "lint"
    nix develop -c "tests"
    latest
    gh  release create --generate-notes --title "v$version" --draft --prerelease
rules:
  preventRootAdditions: true
  uneditableFiles:
    - "./flake.lock"
    - "./package.json"
    - ".conclaude.yaml"
