# Conclaude YAML Configuration for Rust Implementation
# This configuration defines how conclaude handles Claude Code hook events

# Commands to run during Stop hook
# Each line is executed as a separate bash command
stop:
  run: |
    nix fmt
    cargo clippy -- -D warnings -D clippy::pedantic
    cargo test --lib
    cargo build
  # infinite mode - allows Claude to continue automatically
  # When enabled, Claude receives the infinite_message to continue working
  # instead of ending the session after stop hook commands succeed
  infinite: false
  infinite_message: "continue working on the task"

# Validation rules for hook processing
rules:
  # Prevent Claude from creating or modifying files at the repository root
  # Helps maintain clean project structure
  prevent_root_additions: true

  # Files that Claude cannot edit, using glob patterns
  # Examples:
  # - "./package.json" - specific files
  # - "*.md" - file extensions
  # - "src/**/*.ts" - nested patterns
  # - ".env*" - environment files
  # - "docs/**" - entire directories
  uneditable_files:
    # - ".conclaude.yaml"
    - ".envrc"
