stop:
  run: |
    nix build .
    nix develop -c "lint"
    nix develop -c "tests"
rules:
  preventRootAdditions: true
  uneditableFiles:
    - "./flake.lock"
    - "./package.json"
    - ".conclaude.yaml"
