# yaml-language-server: $schema=https://raw.githubusercontent.com/connix-io/conclaude/main/conclaude-schema.json

stop:
    # run: "nix develop -c `lint`"
    commands:
        - message: "failed to run linting"
          run: "nix develop -c lint"
          continueOnError: false

    infinite: false
rules:
    preventRoot: true
    uneditableFiles: []
    toolUsageValidation: []
preToolUse:
    preventAdditions: []
    preventGeneratedFileEdits: true
gitWorktree:
    enabled: false
    autoCreatePR: false
