package config

import (
	"os"
	"path/filepath"
	"testing"

	"gopkg.in/yaml.v3"
)

func TestDefaultConfig(t *testing.T) {
	config := DefaultConfig()

	// Test default values
	if !config.Rules.PreventRootAdditions {
		t.Errorf(
			"Expected PreventRootAdditions to be true, got %v",
			config.Rules.PreventRootAdditions,
		)
	}

	if !config.PreToolUse.PreventGeneratedFileEdits {
		t.Errorf(
			"Expected PreventGeneratedFileEdits to be true, got %v",
			config.PreToolUse.PreventGeneratedFileEdits,
		)
	}

	if config.Stop.Infinite {
		t.Errorf("Expected Infinite to be false, got %v", config.Stop.Infinite)
	}

	if config.GitWorktree.Enabled != false {
		t.Errorf("Expected GitWorktree.Enabled to be false, got %v", config.GitWorktree.Enabled)
	}
}

func TestGenerateDefaultConfigYAML(t *testing.T) {
	yamlStr := GenerateDefaultConfigYAML()

	// Test that it's valid YAML
	var config ConclaudeConfig
	if err := yaml.Unmarshal([]byte(yamlStr), &config); err != nil {
		t.Fatalf("Generated YAML is invalid: %v", err)
	}

	// Test that it matches default config
	defaultConfig := DefaultConfig()
	if config.Rules.PreventRootAdditions != defaultConfig.Rules.PreventRootAdditions {
		t.Error("YAML config doesn't match default config")
	}
}

func TestLoadConfigNotFound(t *testing.T) {
	// Create a temporary directory without config file
	tempDir := t.TempDir()
	originalDir, _ := os.Getwd()

	// Change to temp directory
	if err := os.Chdir(tempDir); err != nil {
		t.Fatalf("Failed to change directory: %v", err)
	}
	defer func() { _ = os.Chdir(originalDir) }()

	config, err := LoadConfig()
	if err != nil {
		t.Fatalf("LoadConfig failed: %v", err)
	}

	// Should return default config when no file found
	defaultConfig := DefaultConfig()
	if config.Rules.PreventRootAdditions != defaultConfig.Rules.PreventRootAdditions {
		t.Error("Expected default config when no file found")
	}
}

func TestLoadConfigWithFile(t *testing.T) {
	tempDir := t.TempDir()
	originalDir, _ := os.Getwd()

	// Change to temp directory
	if err := os.Chdir(tempDir); err != nil {
		t.Fatalf("Failed to change directory: %v", err)
	}
	defer func() { _ = os.Chdir(originalDir) }()

	// Create a test config file
	configContent := `
rules:
  preventRootAdditions: false
  uneditableFiles: 
    - "*.generated.*"
    - "build/**"
stop:
  infinite: true
`

	configPath := filepath.Join(tempDir, ".conclaude.yaml")
	if err := os.WriteFile(configPath, []byte(configContent), 0644); err != nil {
		t.Fatalf("Failed to write config file: %v", err)
	}

	config, err := LoadConfig()
	if err != nil {
		t.Fatalf("LoadConfig failed: %v", err)
	}

	// Test loaded values
	if config.Rules.PreventRootAdditions != false {
		t.Errorf(
			"Expected PreventRootAdditions to be false, got %v",
			config.Rules.PreventRootAdditions,
		)
	}

	if config.Stop.Infinite != true {
		t.Errorf("Expected Infinite to be true, got %v", config.Stop.Infinite)
	}

	if len(config.Rules.UneditableFiles) != 2 {
		t.Errorf("Expected 2 uneditable files, got %d", len(config.Rules.UneditableFiles))
	}
}

func TestExtractFilePath(t *testing.T) {
	tests := []struct {
		name     string
		input    map[string]interface{}
		expected *string
	}{
		{
			name: "file_path key",
			input: map[string]interface{}{
				"file_path": "test.go",
				"content":   "package main",
			},
			expected: stringPtr("test.go"),
		},
		{
			name: "path key",
			input: map[string]interface{}{
				"path":    "src/main.rs",
				"content": "fn main() {}",
			},
			expected: stringPtr("src/main.rs"),
		},
		{
			name: "no file path",
			input: map[string]interface{}{
				"command": "ls -la",
			},
			expected: nil,
		},
		{
			name: "empty file path",
			input: map[string]interface{}{
				"file_path": "",
				"content":   "test",
			},
			expected: nil,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := ExtractFilePath(tt.input)

			switch {
			case tt.expected == nil && result != nil:
				t.Errorf("Expected nil, got %s", *result)
			case tt.expected != nil && result == nil:
				t.Errorf("Expected %s, got nil", *tt.expected)
			case tt.expected != nil && result != nil && *tt.expected != *result:
				t.Errorf("Expected %s, got %s", *tt.expected, *result)
			}
		})
	}
}

func TestIsAutoGeneratedFile(t *testing.T) {
	tests := []struct {
		filePath string
		expected bool
	}{
		{"src/main.go", false},
		{"node_modules/package/index.js", true},
		{"build/output.js", true},
		{"dist/bundle.js", true},
		{"target/debug/main", true},
		{"src/generated/api.go", true},
		{"go.sum", true},
		{"package-lock.json", true},
		{"Cargo.lock", true},
		{"regular-file.lock", false}, // Only exact matches
		{"src/file.generated.ts", true},
		{"coverage/report.html", true},
	}

	for _, tt := range tests {
		t.Run(tt.filePath, func(t *testing.T) {
			result := IsAutoGeneratedFile(tt.filePath)
			if result != tt.expected {
				t.Errorf(
					"IsAutoGeneratedFile(%q) = %v, expected %v",
					tt.filePath,
					result,
					tt.expected,
				)
			}
		})
	}
}

func TestExtractBashCommands(t *testing.T) {
	tests := []struct {
		name     string
		input    map[string]interface{}
		expected []string
	}{
		{
			name: "single command",
			input: map[string]interface{}{
				"command": "ls -la",
			},
			expected: []string{"ls -la"},
		},
		{
			name: "multiple commands with semicolon",
			input: map[string]interface{}{
				"command": "cd /tmp; ls -la; echo done",
			},
			expected: []string{"cd /tmp", "ls -la", "echo done"},
		},
		{
			name: "no command key",
			input: map[string]interface{}{
				"file_path": "test.sh",
			},
			expected: []string{},
		},
		{
			name: "empty command",
			input: map[string]interface{}{
				"command": "",
			},
			expected: []string{},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := ExtractBashCommands(tt.input)

			if len(result) != len(tt.expected) {
				t.Errorf("Expected %d commands, got %d", len(tt.expected), len(result))

				return
			}

			for i, expected := range tt.expected {
				if i >= len(result) || result[i] != expected {
					t.Errorf("Expected command[%d] to be %q, got %q", i, expected, result[i])
				}
			}
		})
	}
}

// Helper function to create string pointer
func stringPtr(s string) *string {
	return &s
}
